require([
   "dojo/_base/lang",
   "dojo/on",
   "dojo/ready",
   "dojo/parser",
   "dojo/_base/fx",
   "dojo/dom",
   "dojo/dom-construct",
   "dojo/dom-attr",
   "dojo/dom-style",
   "dijit/layout/ContentPane",
   "dijit/layout/BorderContainer",
   "dijit/layout/TabContainer",
   "dijit/form/Button",
   "dijit/form/DateTextBox",
   "dijit/form/TextBox",
   "dijit/form/ComboBox",
   "dojox/grid/EnhancedGrid",
   "dijit/form/Select",
   "dijit/form/ValidationTextBox",
   "dijit/form/FilteringSelect",
   "dijit/Dialog",
   "dojo/store/Memory",
   "dojo/domReady!",
], function (
   lang,
   on,
   ready,
   parser,
   fx,
   dom,
   domConstruct,
   domAttr,
   style,
   ContentPane,
   BorderContainer,
   TabContainer,
   Button,
   DateTextBox,
   TextBox,
   ComboBox,
   EnhancedGrid,
   Select,
   ValidationTextBox,
   FilteringSelect,
   Dialog,
   Memory,
   domReady
) {
   let usuarios = [
      {
         id: 1,
         username: "matias",
         nombre: "Matias Romera",
         edad: "24",
         password: "123",
         rol: "it",
         email: "matias@capgemini.com",
      },
      {
         id: 2,
         username: "fernando",
         nombre: "Fernando Scroppo",
         edad: "24",
         password: "123",
         rol: "it",
         email: "fernando@capgemini.com",
      },
      {
         id: 3,
         username: "noelia",
         nombre: "Noelia Escalier",
         edad: "24",
         password: "123",
         rol: "it",
         email: "noelia@capgemini.com",
      },
      {
         id: 4,
         username: "braian",
         nombre: "Braian Almada",
         edad: "24",
         password: "123",
         rol: "it",
         email: "braian@capgemini.com",
      },
      {
         id: 5,
         username: "gonzalo",
         nombre: "Gonzalo Delgado",
         edad: "24",
         password: "123",
         rol: "it",
         email: "gonzalo@capgemini.com",
      },
      { id: 6, username: "rocio", nombre: "Rocio Badessi", edad: "24", password: "123", rol: "hr", email: "rocio@capgemini.com" },
      {
         id: 7,
         username: "florencia",
         nombre: "Florencia Mazza",
         edad: "24",
         password: "123",
         rol: "hr",
         email: "florencia@capgemini.com",
      },
   ];

   store = new Memory({ data: usuarios });
});
